name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: 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
        BRANCH: master
        FOLDER: build
        BUILD_SCRIPT: yarn && yarn build